### ISSUE TITLE
require modules instead of namespace

### ISSUE THREAD

**Issue by pablomayobre** [tjakka5/Babble#3]
As discussed in Discord:

Namespaces make weak relationships between modules. This means that for `dialogue.lua` to work `init.lua` needs to correctly place `node.lua` in `Namespace.node` which is a possible point of failure.

You may later revisit `node.lua` and or `init.lua` and then `dialogue.lua` would stop working because it can't find what it's searching for in `Namespace.node`

Directly requiring `node.lua` in `dialogue.lua` would fix this issue, since you can clearly see what file depends on what other file.

Namespaces are generally useful when you need to require tens of files in a single file, or when you have recursive dependencies. But neither is the case, Babble is pretty module and all the files require 1 other file or none at all.

**Comment by Keyslam** [comment]
Namespace has been removed. Files now have to explicitly require their dependencies. Init.lua now contains a table that is filled and returned with all modules.
