### ISSUE TITLE
Separate components somehow

### ISSUE THREAD

**Issue by Keyslam** [tjakka5/Babble#4]
Currently all components are stored in one file. This is messy and hard to maintain as the number of components increases.

We should look into a way to easily support and add new components. Perhaps a Component constructor.

**Comment by pablomayobre** [comment]
It would be cool if we could register components to a specific dialogue

**Comment by Keyslam** [comment]
Components have been separated into a folder named "Components". This folder also holds a init.lua that returns a table with all the components.
