### ISSUE TITLE
Use setmetatable instead of Middleclass

### ISSUE THREAD

**Issue by pablomayobre** [tjakka5/Babble#5]
It's generally a good idea to diminish the number of dependencies in a library.

Middleclass is a complete class library, which has inheritance, mixins and complete support for metamethods, but none of this features are needed for Babble.

Also as seen [here](https://mainstrea.ml/blog/moonscript-vs-popular-lua-oo-libs) it's one of the slowest class libraries (due to the added complexity).

All the uses of Middleclass could easily be replaced with setmetatable and constructor functions

**Comment by Keyslam** [comment]
I've replaced middleclass with a custom light weight class implementation.

**Comment by pablomayobre** [comment]
Really nice class implementation! It's really minimal, I may use it in some of my projects
