### ISSUE TITLE
scripts + links/conditions + options = ???

### ISSUE THREAD

**Issue by pablomayobre** [tjakka5/Babble#6]
We discussed some of this in Discord, scripts, links and options functionality is pretty similar and could be merged into a single thing.

Components are currently able to return `true` to continue evaluating the node, or `false` to halt, which means that the component will be updated until it returns `true`.

My request is the addition of being able to return a string value, that represents the `Node` to move to.

This would make it possible for conditions and more complex stuff to be written inside of this nodes
```lua
dialogue:coolstuff(function (node, dt, ...)
  if love.keyboard.isDown('a') then
    return 'dialogue1'
  elseif love.keyboard.isDown('b') then
    return 'dialogue2'
  elseif love.keyboard.isDown('space') then
    return true
  else
    return false
  end
end, ...)
```

`coolstuff` is a placeholder name haha. Note that any other argument passed to `coolstuff` will be passed to the callback after `node` and `dt`, making it possible to reuse the callback functions as much as possible

**Comment by pablomayobre** [comment]
I could use this `coolstuff` as `link` by doing:

```lua
local condition_equal = function (target, a, b)
  return a == b and target or true
end

dialogue:coolstuff(condition_equal, "nodeid", x, 100)
```

More complex stuff could be done too, but this show how it could easily replace link, while the example in the main post details a possible implementation of `options`

Of course using it as a `script` is trivial

**Comment by Keyslam** [comment]
Conditions have been replaced with a function argument, this should allow for the functionality that you have proposed.

Note that your second example is not possible, due to x being a copy at the moment it is defined, and thus can not be changed in dialogue runtime.

**Comment by pablomayobre** [comment]
Yes I knew that, but let it be since that was the behaviour of conditions back then.
