### ISSUE TITLE
Use every link as a "returning link"

### ISSUE THREAD

**Issue by Keyslam** [tjakka5/Babble#7]
Originally link would have a argument to function as a "returning link", in the way that dialogue would snap back to the current node (and position) when the branch finished.

Instead we should handle every link as a returning link, and add a component that notes the end of the dialogue.

This will allow for easier to use and more advanced dialogue.

The node stack will require to keep track of the current components to make this feasible with recurring / looping nodes.

**Comment by pablomayobre** [comment]
On this note, currently nodes store position information, so doing something like:

```lua
d = Babble.dialogue()
  :startNode("first")
    :print("one")
    :link(function () return "second" end)
    :print("three")
  :endNode()

  :startNode("second")
    :print("two")
    :link(function ()
      if not done then
        done = true
        return "first"
      end
    end)
  :endNode()
```

Would print:
```
one
two
three
```
Instead of the expected
```
one
two
one
two
three --This would only be printed if links are returning links
```
EDIT: This is probably related to #1
